#include "servos.h"

// Includes the library declarations needed to control the GPIO pins.
#include <lgpio.h>

// Stores the GPIO controller handle. -1 means it is not open.
static int gpioHandle = -1;

bool inicializarServos()
{
    // Opens gpiochip0 and returns a handle used to access it.
    // Returns 0 or a positive integer on success: ALL are valid handles.
    // Returns a negative error code on failure.
    // Therefore, we check gpioHandle < 0, not gpioHandle != 0.
    gpioHandle = lgGpiochipOpen(0);
    if (gpioHandle < 0) {
        return false;
    }

    // Reserves both GPIO pins as outputs, initially LOW.
    // Claim functions return 0 on success or a negative error code.
    int resultado = lgGpioClaimOutput(gpioHandle, 0, GPIO_PAN, 0);
    int resultado2 = lgGpioClaimOutput(gpioHandle, 0, GPIO_TILT, 0);

    // Fails if either GPIO could not be reserved.
    if (resultado < 0 or resultado2 < 0) {
        // Closing the controller also releases any GPIO already reserved.
        lgGpiochipClose(gpioHandle);
        gpioHandle = -1;
        return false;
    }

    return true;
}

bool definirPulso(int gpio, int pulso_us)
{
    // Rejects requests before the controller has been opened.
    if (gpioHandle < 0) {
        return false;
    }

    // Accepts only the pins selected in servos.h.
    if (gpio != GPIO_PAN and gpio != GPIO_TILT) {
        return false;
    }

    // Invalid requests leave any existing pulse signal unchanged.
    if (pulso_us < PULSO_MIN_US or pulso_us > PULSO_MAX_US) {
        return false;
    }

    // Repeats the control pulse at 50 Hz (once every 20 ms).
    // The library repeats pulses continuously; no manual loop is needed.
    int resultadoPWM = lgTxServo(gpioHandle, gpio, pulso_us, 50, 0, 0);

    // Unlike a claim operation, success may return a positive queue count.
    return resultadoPWM >= 0;
}

void terminarServos()
{
    if (gpioHandle < 0) {
        return;
    }

    // A zero pulse width stops the pulses generated by the library.
    lgTxServo(gpioHandle, GPIO_PAN, 0, 50, 0, 0);
    lgTxServo(gpioHandle, GPIO_TILT, 0, 50, 0, 0);

    // Closes the controller and releases all GPIO pins reserved through it.
    lgGpiochipClose(gpioHandle);
    gpioHandle = -1;
}
