#pragma once

// Servos typically receive one control pulse every 20 ms (20000 us).
constexpr int PERIODO_US = 20000;

// Initial control range: 1000 to 2000 us.
// A pulse width of 1500 us requests the middle position.
// Verify the limits on the actual servo and assembly.
constexpr int PULSO_MIN_US = 1000;
constexpr int PULSO_CENTRO_US = 1500;
constexpr int PULSO_MAX_US = 2000;

constexpr int GPIO_PAN = 18;
constexpr int GPIO_TILT = 19;

// Opens the GPIO controller, which gives us access to the GPIO pins.
// Pins must be configured as inputs or outputs.
// Reserves the servo pins as outputs to send control pulses.
// Returns true on success or false on failure.
bool inicializarServos();

// Selects the GPIO pin and requests a servo position using pulse width.
// gpio: BCM GPIO number, not the physical connector pin number.
// pulso_us: pulse width in microseconds, within our 1000–2000 us range.
// Returns true if accepted or false if validation or pulse generation fails.
bool definirPulso(int gpio, int pulso_us);

// Stops the pulses generated by the library.
// Releases the GPIO pins we reserved.
// Closes the controller opened by inicializarServos().
void terminarServos();